pub const Button = enum(u32) {
    left = 0x110,
    right = 0x111,
    middle = 0x112,
};

pub const PointerAction = enum { move_window, resize_window };

pub const KeybindingAction = union(enum) {
    close_window: void,
    toggle_fullscreen: void,
    toggle_maximize_column: void,
    adjust_window_width: f32,
    set_window_width: f32,
    focus_window_left: void,
    focus_window_or_output_left: void,
    focus_window_right: void,
    focus_window_or_output_right: void,
    move_window_left: void,
    move_window_right: void,
    move_window_left_or_to_output_left: void,
    move_window_right_or_to_output_right: void,
    toggle_workspace_floating: void,
    focus_workspace_above: void,
    focus_workspace_below: void,
    focus_workspace_or_output_above: void,
    focus_workspace_or_output_below: void,
    focus_workspace_previous: void,
    focus_workspace_number: usize,
    move_window_to_workspace_above: void,
    move_window_to_workspace_below: void,
    move_window_to_workspace_or_output_above: void,
    move_window_to_workspace_or_output_below: void,
    move_window_to_workspace_number: usize,
    focus_output_left: void,
    focus_output_right: void,
    focus_output_above: void,
    focus_output_below: void,
    move_window_to_output_left: void,
    move_window_to_output_right: void,
    move_window_to_output_above: void,
    move_window_to_output_below: void,
    exit: void,
    reload_config: void,
    enter_overview: void,
    spawn: []const []const u8,
};
